amu_bachelor_thesis/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('amu_bachelor_thesis/', include('amu_bachelor_thesis_app.urls'))
]

amu_bachelor_thesis_app/urls.py
from django.urls import path, include
from django.views.generic.base import TemplateView

from .views import thesis_views, thesis_propositions_views, notifications_views, lecturer_views, students_views, \
    auth_views

app_name = 'amu_bachelor_thesis'
urlpatterns = [
    path('', TemplateView.as_view(template_name='amu_bachelor_thesis_app/home.html'), name='home'),
    # AUTH ROUTES
    path('accounts/', include('django.contrib.auth.urls')),
    path('login_redirect', auth_views.login_redirect, name='login_redirect'),
    # STUDENT ROUTES
    path('student/<int:pk>', students_views.StudentProfile.as_view(), name='student_profile'),
    # LECTURER ROUTES
    path('lecturer/<int:pk>', lecturer_views.LecturerProfile.as_view(), name='lecturer_profile'),
    path('lecturer/edit', lecturer_views.edit_lecturer, name='edit_lecturer'),
    # THESIS ROUTES
    path('manage_thesis', thesis_views.ManageThesis.as_view(), name='manage_thesis'),
    path('thesis/create', thesis_views.create_thesis, name='create_thesis'),
    path('thesis/edit/<int:thesis_id>', thesis_views.edit_thesis, name="edit_thesis"),
    path('search_engine', thesis_views.ThesisSearchEngine.as_view(), name="search_engine"),
    path('thesis/<int:pk>', thesis_views.ThesisView.as_view(), name="thesis"),
    path('thesis/<int:thesis_id>/select', thesis_views.select_thesis, name="select_thesis"),
    path('thesis/<int:thesis_id>/unselect', thesis_views.unselect_thesis, name="unselect_thesis"),
    path('thesis/<int:thesis_id>/remove', thesis_views.remove_thesis, name="remove_thesis"),
    # THESIS PROPOSITION ROUTES
    path('thesis_proposition/<int:pk>', thesis_propositions_views.ThesisPropositionView.as_view(), name="thesis_proposition"),
    path('thesis_proposition/<int:thesis_proposition_id>/accept', thesis_propositions_views.lecturer_accept_thesis_proposition, name="accept_thesis_proposition"),
    path('thesis_proposition/<int:thesis_proposition_id>/discard', thesis_propositions_views.lecturer_discard_thesis_proposition, name="discard_thesis_proposition"),
    path('thesis_proposition/<int:thesis_proposition_id>/discard_own', thesis_propositions_views.student_discard_own_thesis_proposition, name="discard_own_thesis_proposition"),
    path('thesis_proposition/<int:thesis_proposition_id>/resend', thesis_propositions_views.student_resend_own_thesis_proposition, name="resend_thesis_proposition"),
    path('manage_thesis_propositions', thesis_propositions_views.ManageThesisPropositions.as_view(), name="manage_thesis_propositions"),
    path('thesis_proposition/create', thesis_propositions_views.create_thesis_proposition, name='create_thesis_proposition'),
    path('thesis_proposition/<int:thesis_proposition_id>/edit', thesis_propositions_views.edit_thesis_proposition, name='edit_thesis_proposition'),
    path('lecturer_manage_thesis_propositions', thesis_propositions_views.lecturer_manage_thesis_proposition, name='lecturer_manage_thesis_propositions'),
    # NOTIFICATION ROUTES
    path('notifications', notifications_views.NotificationsView.as_view(), name='notifications'),
    path('notifications/history', notifications_views.NotificationsHistoryView.as_view(), name='notifications_history'),
    path('notifications_getcounter', notifications_views.notifications_get_counter, name='notifications_get_counter')
]

amu_bachelor_thesis_app/views/auth_views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse

from amu_bachelor_thesis_app.models import User


@login_required
def login_redirect(request):
    if not request.user.is_authenticated:
        return HttpResponse('Unauthorized', status=401)
    if request.user.role == User.SUPERUSER:
        return HttpResponseRedirect(reverse('amu_bachelor_thesis:home'))
    return HttpResponseRedirect(reverse('amu_bachelor_thesis:search_engine'))

amu_bachelor_thesis_app/views/lecturer_views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import generic
from amu_bachelor_thesis_app.models import Lecturer


@method_decorator(login_required, name='dispatch')
class LecturerProfile(generic.DetailView):
    model = Lecturer
    template_name = 'amu_bachelor_thesis_app/lecturer/lecturer_profile.html'


@login_required
@user_passes_test(lambda user: user.is_lecturer())
def edit_lecturer(request):
    lecturer = request.user.lecturer
    if request.method == 'GET':
        return render(request, 'amu_bachelor_thesis_app/lecturer/edit_lecturer.html', {'lecturer': lecturer})
    elif request.method == 'POST':
        lecturer_degree = request.POST.get('lecturer_degree')
        lecturer_description = request.POST.get('lecturer_description')
        lecturer_interests = request.POST.get('lecturer_interests')
        lecturer.degree = lecturer_degree
        lecturer.description = lecturer_description
        lecturer.interests = lecturer_interests
        lecturer.save()
        return HttpResponseRedirect(reverse('amu_bachelor_thesis:lecturer_profile', args=(lecturer.user_id,)))
    else:
        return HttpResponse('Method not allowed', status=405)

amu_bachelor_thesis_app/views/notifications_views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.utils.decorators import method_decorator
from django.views import generic
from amu_bachelor_thesis_app.models import Notification


@method_decorator(login_required, name='dispatch')
class NotificationsView(generic.ListView):
    model = Notification
    template_name = 'amu_bachelor_thesis_app/notification/notifications.html'
    context_object_name = 'notifications'

    def get_queryset(self):
        notifications = Notification.objects.filter(recipient=self.request.user, is_seen=False).order_by('-date')
        for notification in notifications:
            notification.is_seen = True
            notification.save()
        return notifications


@method_decorator(login_required, name='dispatch')
class NotificationsHistoryView(generic.ListView):
    model = Notification
    template_name = 'amu_bachelor_thesis_app/notification/notifications-history.html'
    context_object_name = 'notifications'
    paginate_by = 15

    def get_queryset(self):
        return Notification.objects.filter(recipient=self.request.user, is_seen=True).order_by('-date')


@login_required
def notifications_get_counter(request):
    number_of_unread_notifications = Notification.objects.filter(recipient=request.user, is_seen=False).count()
    return JsonResponse({"unread_notifications": number_of_unread_notifications}, status=200)

amu_bachelor_thesis_app/views/students_views.py
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.views import generic

from amu_bachelor_thesis_app.models import Student


@method_decorator(login_required, name='dispatch')
class StudentProfile(generic.DetailView):
    model = Student
    template_name = 'amu_bachelor_thesis_app/student/student_profile.html'

amu_bachelor_thesis_app/views/thesis_propositions_views.py
from django.contrib.auth.decorators import login_required, user_passes_test
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.utils.decorators import method_decorator
from django.views import generic
from django.urls import reverse
from django.utils import timezone
from amu_bachelor_thesis_app.models import ThesisProposition, Lecturer, Student
from amu_bachelor_thesis_app.notification_helper import NotificationHelper


@method_decorator(login_required, name='dispatch')
@method_decorator(user_passes_test(lambda user: user.is_student()), name='dispatch')
class ManageThesisPropositions(generic.ListView):
    model = ThesisProposition
    paginate_by = 10
    template_name = 'amu_bachelor_thesis_app/thesis_proposition/manage_thesis_propositions.html'

    def get_queryset(self):
        return ThesisProposition.objects.filter(student_id=self.request.user.id).order_by('-edited_at', '-created_at')


@login_required
@user_passes_test(lambda user: user.is_student())
def create_thesis_proposition(request):
    if request.method == 'GET':
        lecturers = Lecturer.objects.all()
        return render(request,
                      'amu_bachelor_thesis_app/thesis_proposition/create_thesis_proposition.html',
                      {'lecturers': lecturers})
    elif request.method == 'POST':
        if request.user.student.has_thesis():
            return HttpResponse("Student has thesis", 401)
        title = request.POST.get('thesis_proposition_title')
        if not title:
            return HttpResponse('Title is required', 400)
        lecturer_id = request.POST.get('thesis_proposition_lecturer_id')
        lecturer = get_object_or_404(Lecturer, pk=lecturer_id)
        description = request.POST.get('thesis_description')
        if not description:
            description = ''
        new_thesis_proposition = ThesisProposition(title=title, description=description, created_at=timezone.now(),
                                                   lecturer=lecturer, student=request.user.student, is_active=True)
        new_thesis_proposition.save()
        NotificationHelper.send_student_created_proposition_notification(new_thesis_proposition)
        return HttpResponseRedirect(reverse('amu_bachelor_thesis:manage_thesis_propositions'))
    else:
        return HttpResponse('Method not allowed', status=405)


@login_required
@user_passes_test(lambda user: user.is_student())
def edit_thesis_proposition(request, thesis_proposition_id):
    thesis_proposition = get_object_or_404(ThesisProposition, pk=thesis_proposition_id)
    if thesis_proposition.student != request.user.student:
        return HttpResponse('Permission denied', 403)
    if request.method == 'GET':
        lecturers = Lecturer.objects.all()
        return render(request,
                      'amu_bachelor_thesis_app/thesis_proposition/edit_thesis_proposition.html',
                      {'lecturers': lecturers, 'thesis_proposition': thesis_proposition})
    elif request.method == 'POST':
        title = request.POST.get('thesis_proposition_title')
        if not title:
            return HttpResponse('Title is required', 400)
        description = request.POST.get('thesis_proposition_description')
        if not description:
            description = ''
        thesis_proposition.title = title
        thesis_proposition.description = description
        thesis_proposition.edited_at = timezone.now()
        thesis_proposition.save()
        if thesis_proposition.is_active:
            NotificationHelper.send_student_edited_proposition_notification(thesis_proposition)
        return HttpResponseRedirect(reverse('amu_bachelor_thesis:manage_thesis_propositions'))
    else:
        return HttpResponse('Method not allowed', status=405)


@login_required
@user_passes_test(lambda user: user.is_lecturer())
def lecturer_manage_thesis_proposition(request):
    lecturer = request.user.lecturer
    students = Student.objects.filter(thesisproposition__lecturer_id=lecturer, thesisproposition__is_active=True).distinct()
    thesis_propositions_dictionary = {}
    for student in students:
        thesis_propositions_dictionary[student.user_id] = ThesisProposition.objects.filter(student_id=student.user_id, lecturer_id=lecturer.user_id, is_active=True)
    template_name = 'amu_bachelor_thesis_app/thesis_proposition/lecturer_manage_thesis_propositions.html'
    return render(request, template_name, {
        'students': students,
        'thesis_propositions_dictionary': thesis_propositions_dictionary
    })


@method_decorator(login_required, name='dispatch')
class ThesisPropositionView(generic.DetailView):
    model = ThesisProposition
    template_name = "amu_bachelor_thesis_app/thesis_proposition/thesis_proposition.html"
    context_object_name = 'thesis_proposition'


@login_required
@user_passes_test(lambda user: user.is_lecturer())
def lecturer_accept_thesis_proposition(request, thesis_proposition_id):
    thesis_proposition = get_object_or_404(ThesisProposition, pk=thesis_proposition_id)
    if thesis_proposition.lecturer != request.user.lecturer:
        return HttpResponse('Permission denied', 403)
    student = thesis_proposition.student
    thesis = thesis_proposition.get_thesis()
    thesis.save()
    thesis_proposition.delete()
    student.discard_all_propositions()
    NotificationHelper.send_lecturer_accepted_proposition_notification(thesis)
    return HttpResponseRedirect(reverse('amu_bachelor_thesis:lecturer_manage_thesis_propositions'))


@login_required
@user_passes_test(lambda user: user.is_lecturer())
def lecturer_discard_thesis_proposition(request, thesis_proposition_id):
    thesis_proposition = get_object_or_404(ThesisProposition, pk=thesis_proposition_id)
    if thesis_proposition.lecturer != request.user.lecturer:
        return HttpResponse('Permission denied', 403)
    thesis_proposition.is_active = False
    thesis_proposition.save()
    NotificationHelper.send_lecturer_discarded_proposition_notification(thesis_proposition)
    return HttpResponseRedirect(reverse('amu_bachelor_thesis:lecturer_manage_thesis_propositions'))


@login_required
@user_passes_test(lambda user: user.is_student())
def student_discard_own_thesis_proposition(request, thesis_proposition_id):
    thesis_proposition = get_object_or_404(ThesisProposition, pk=thesis_proposition_id)
    if thesis_proposition.student != request.user.student:
        return HttpResponse('Permission denied', 403)
    thesis_proposition.is_active = False
    thesis_proposition.save()
    NotificationHelper.send_student_discard_proposition_notification(thesis_proposition)
    return HttpResponseRedirect(reverse('amu_bachelor_thesis:manage_thesis_propositions'))


@login_required
@user_passes_test(lambda user: user.is_student())
def student_resend_own_thesis_proposition(request, thesis_proposition_id):
    thesis_proposition = get_object_or_404(ThesisProposition, pk=thesis_proposition_id)
    if thesis_proposition.student != request.user.student:
        return HttpResponse('Permission denied', 403)
    if request.user.student.has_thesis():
        return HttpResponse("Student has thesis", 401)
    thesis_proposition.is_active = True
    thesis_proposition.save()
    NotificationHelper.send_student_created_proposition_notification(thesis_proposition)
    return HttpResponseRedirect(reverse('amu_bachelor_thesis:manage_thesis_propositions'))

amu_bachelor_thesis_app/templates/amu_bachelor_thesis_app/shell/footer.html
<footer class="footer has-text-centered mt-6">
    Uniwersytet im. Adama Mickiewicza w Poznaniu
    <a href="https://nieruchalski.pl">Michał Nieruchalski</a>
    2021
</footer>

amu_bachelor_thesis_app/templates/amu_bachelor_thesis_app/shell/navbar.html
{% load lecturer %}
{% load helpers %}
<nav class="navbar" role="navigation">
    <div class="navbar-brand">
        <a class="navbar-item" href="{% url 'amu_bachelor_thesis:home' %}">
            <h1>AMU Bachelor Thesis</h1>
        </a>

        <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
        </a>
    </div>
    <div id="navbarBasicExample" class="navbar-menu">
        <div class="navbar-start">
            {% if user.is_authenticated %}
                <a class="navbar-item" href="{% url 'amu_bachelor_thesis:search_engine' %}">Wyszukiwarka tematów</a>
            {% endif %}
            {% if user.is_student %}
                <a class="navbar-item" href="{% url 'amu_bachelor_thesis:manage_thesis_propositions' %}">Proponowanie tematu</a>
            {% endif %}
            {% if user.is_lecturer %}
                <a class="navbar-item" href="{% url 'amu_bachelor_thesis:lecturer_manage_thesis_propositions' %}">
                    Propozycje studentów ({% count_thesis_propositions user.lecturer %})
                </a>
            {% endif %}
        </div>
    </div>
    <div class="navbar-end">
        <div class="navbar-end">
            {% if user.is_authenticated %}
                {% has_notifications user as show_notification_dot %}
                <a href="{% url 'amu_bachelor_thesis:notifications' %}" id="big-notification-dot-container" class="navbar-item {% if show_notification_dot %}hidden{% endif %}">
                    <div class="notification-dot big">
                        {% get_number_of_notifications user %}
                    </div>
                </a>
                <div class="navbar-item has-dropdown is-hoverable">
                    <a class="navbar-link">{{ user }}</a>
                    <div class="navbar-dropdown is-right">
                        {% if user.is_student %}
                            <a class="navbar-item" href="{% url 'amu_bachelor_thesis:student_profile' user.id %}">Profil</a>
                        {% elif user.is_lecturer %}
                            <a class="navbar-item" href="{% url 'amu_bachelor_thesis:lecturer_profile' user.id %}">Profil</a>
                            <a class="navbar-item" href="{% url 'amu_bachelor_thesis:manage_thesis' %}">Zarządzanie tematami</a>
                        {% endif %}
                        <a class="navbar-item" href="{% url 'amu_bachelor_thesis:notifications' %}">
                            <span>Powiadomienia</span>
                            <div id="small-notification-dot" class="notification-dot small {% if show_notification_dot %}hidden{% endif %}">
                                {% get_number_of_notifications user %}
                            </div>
                        </a>
                        <hr class="navbar-divider">
                        {% if user.is_superuser %}
                            <a class="navbar-item" href="{% url 'admin:index' %}">
                                Zarządzanie użytkownikami
                            </a>
                        {% endif %}
                        <a class="navbar-item" href="{% url 'amu_bachelor_thesis:logout' %}">
                            Wyloguj się
                        </a>
                    </div>
                </div>
            {% else %}
                <div class="navbar-item">
                    <div class="buttons">
                        <a class="button is-primary" href="{% url 'amu_bachelor_thesis:login' %}">
                            Zaloguj się
                        </a>
                    </div>
                </div>
            {% endif %}

        </div>
    </div>
</nav>

amu_bachelor_thesis_app/templates/amu_bachelor_thesis_app/shell/pagination.html
{% load pagination %}
<hr>
<nav class="pagination">
    {% if page_obj.has_previous %}
        <a href="?{% url_replace page=page_obj.previous_page_number %}" class="pagination-previous">&lt;&lt; Poprzednia strona</a>
    {% else %}
        <a disabled class="pagination-previous">&lt;&lt; Poprzednia strona</a>
    {% endif %}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}" class="pagination-next">Następna strona &gt;&gt;</a>
    {% else %}
        <a disabled class="pagination-next">Następna strona &gt;&gt;</a>
    {% endif %}

    <div class="pagination-list">
      Strona {{ page_obj.number }} z {{ page_obj.paginator.num_pages }}
    </div>
</nav>